services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: assign
      POSTGRES_PASSWORD: qweasd
      POSTGRES_DB: assign
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data`

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin 
    ports:
      - "8080:80"
    depends_on:
      - db
volumes:
  postgres_data:


